### PR TITLE
Fix: correctly expand delays

### LINKED ISSUE #141: Delays aren't correctly expanded
We've found that the following program:

```
DEFCAL I q:
    DELAY q 4e-8
    I 0
```

which _should_ expand into `DELAY 0 4e-8`, instead erroneously leaves the variable `q` unresolved:

```
failures:

---- program::calibration::tests::expansion stdout ----
thread 'program::calibration::tests::expansion' panicked at 'assertion failed: `(left == right)`
  left: `"DELAY q 4e-8\n"`,
 right: `"DELAY 0 4e-8\n"`', src/program/calibration.rs:407:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by genos**
Closes #141 

This adds one test case, which currently fails:

```
failures:

---- program::calibration::tests::expansion stdout ----
thread 'program::calibration::tests::expansion' panicked at 'assertion failed: `(left == right)`
  left: `"DELAY q 4e-8\n"`,
 right: `"DELAY 0 4e-8\n"`', src/program/calibration.rs:407:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

and subsequently modifies `CalibrationSet.expand` to handle `DELAY` instructions similarly to `GATE` instructions.

### CODE REVIEW

File: src/program/calibration.rs [hunk 1]
```diff
@@ -115,6 +115,19 @@ impl CalibrationSet {
                                     }
                                 }
                             }
+                            if let Instruction::Delay(Delay { qubits, .. }) = instruction {
```
Comment (kalzoo) [inline src/program/calibration.rs:118]: Can you switch this to a `match` and incorporate the `Gate`, now that it's the second case to handle?

In fact, they can be the same match arm with `|`, since `qubits` is of the same type and the code is the same.

Comment (genos) [reply src/program/calibration.rs]: Great call! See fb04b8f

**Review by kalzoo — APPROVED** [review]
Thanks @genos !
