### PR TITLE
fix: Program equality is sensitive to the order of calibration instructions.

### LINKED ISSUE #356: CalibrationSet equality should be sensitive to ordering.
#352 made CalibrationSet equality insensitive to ordering. Per [Kalan's follow-up](https://github.com/rigetti/quil-rs/pull/352#issuecomment-2059501648), calibration order should be taken into account, as ordering determines precedence when multiple calibrations match the same instruction. The example:

```
DEFCAL A(%x, pi):
   ...

DEFCAL A(pi, %x):
   ...

A(pi, pi) # expands into one or the other based on ordering
```

### PR DESCRIPTION
**Pull request by MarquessV**
closes #356

### CODE REVIEW

File: quil-rs/src/program/calibration_set.rs [hunk 1]
```diff
@@ -236,14 +210,14 @@ mod tests {
...
-    fn test_equality() {
+    fn test_order_sensitive_equality() {
         let mut set1 = CalibrationSet::new();
         let mut set2 = CalibrationSet::new();
         let calib1 = TestCalibration::new("1", None);
         let calib2 = TestCalibration::new("2", None);
         set1.extend(vec![calib1.clone(), calib2.clone()]);
         set2.extend(vec![calib2, calib1]); // Reverse order
-        assert_eq!(set1, set2); // They should be equal
+        assert!(set1 != set2)
```
Comment (kalzoo) [inline quil-rs/src/program/calibration_set.rs:220]:
```suggestion
        assert_ne!(set1, set2)
```

**Review by kalzoo — APPROVED** [review]
