### PR TITLE
fix!: CalibrationSet's and Program's will be considered equal if they contain the same set of calibrations, regardless of order.

### LINKED ISSUE #351: Program equality is sensitive to calibration ordering
When checking if two programs are equal, calibrations should be compared as orderless sets. Calibrations are global state, so the order of them should not matter.

`quil-rs` current `Program` equality logic respects the order of calibrations (and possibly waveforms), which is incorrect.

### PR DESCRIPTION
**Pull request by MarquessV**
I've reworked `CalibrationSet` to actually be a set, where existence in the set is keyed on the calibrations "signature" (e.g. the fields determine the instructions they expand into). In addition, the set maintains insertion order, but disregards order during equality checks. This is to keep program serialization deterministic, while recognizing that the order of calibrations doesn't matter in the semantic meaning of the program.

This required a custom data structure for a few reasons:

1. We care about calibration equality on two different levels: "signature" and equality of contents. This makes using something like an `IndexSet` impossible. To prevent duplicate signatures in a set, we'd have to defined `Hash` and thus `Eq` in terms of the signature. However, when comparing the equality of two calibration sets, we care both about the signature and the contents of the calibration, which would conflict with the definition of `Eq` needed to support using a set.
2. We can't use a `HashMap`, because program serialization wouldn't be deterministic. `BTreeMap` isn't supported by calibrations because there is no clear way to define `Ord` for them, and `IndexMap` defines equality on the order of contents in the map, which leaves us with the same problem we are trying to solve.

Closes #351

### CODE REVIEW

File: quil-rs/src/program/calibration.rs [hunk 1]
```diff
@@ -33,8 +33,8 @@ use super::ProgramError;
 /// A collection of Quil calibrations (`DEFCAL` instructions) with utility methods.
 #[derive(Clone, Debug, Default, PartialEq)]
 pub struct CalibrationSet {
-    pub calibrations: Vec<Calibration>,
-    pub measure_calibrations: Vec<MeasureCalibrationDefinition>,
+    pub calibrations: HashMap<String, Calibration>,
+    pub measure_calibrations: HashMap<(String, Option<Qubit>), MeasureCalibrationDefinition>,
```
Comment (Shadow53) [inline quil-rs/src/program/calibration.rs:37]: According to [the spec](https://quil-lang.github.io/#12-6Defining-Calibrations), a calibration "key" should be a combination of name, parameters, and qubits. Essentially, it seems that the entire string after `DEFCAL` is important for disambiguating calibrations.

Comment (Shadow53) [reply quil-rs/src/program/calibration.rs:37]: Should also note that any tests using `Debug` output, e.g. with `insta`, may have unexpected test failures due to the random ordering of `HashMap`. (This can be worked around with `pretty_assertions_sorted`, but worth noting).

Possibly a better solution is to keep it as a `Vec`, but make the fields private and use methods to ensure that the items in the `Vec` are always sorted. Using `Vec::sort_by(_cached)_key` makes the most sense to me.

**Comment by MarquessV** [comment]
Remaining CI checks will be fixed when #348 can be merged.

File: quil-rs/src/program/calibration.rs (hunk 1 above)
Comment (MarquessV) [reply quil-rs/src/program/calibration.rs]: Turns out existing maps and sets don't really handle the particular needs of how we want these calibration sets to work w/ a program, so I created a custom set, backed by a Vec.

**Comment by MarquessV** [comment]
cc: @mhodson-rigetti does this seem sound to you? Does it meet your expectations of how calibrations should work in a program?

**Comment by mhodson-rigetti** [comment]
> cc: @mhodson-rigetti does this seem sound to you? Does it meet your expectations of how calibrations should work in a program?

Yes, this describes the expected behavior perfectly.

File: quil-rs/src/program/calibration.rs [hunk 2]
```diff
@@ -58,15 +57,26 @@ impl<'a> MatchedCalibration<'a> {
...
 }
 
-impl CalibrationSet {
-    /// Return all [`Calibration`]s in the set
-    pub fn calibrations(&self) -> &[Calibration] {
-        self.calibrations.as_ref()
+impl Calibrations {
+    /// Return a vector containing a reference to all [`Calibration`]s in the set.
+    pub fn calibrations(&self) -> Vec<&Calibration> {
+        self.calibrations.iter().collect()
```
Comment (Shadow53) [inline quil-rs/src/program/calibration.rs:63]:
```suggestion
    /// Return a vector containing a reference to all [`Calibration`]s in the set.
    pub fn calibrations(&self) -> Vec<&Calibration> {
        self.iter_calibrations().collect()
```

File: quil-rs/src/program/calibration.rs [hunk 3]
```diff
@@ -58,15 +57,26 @@ impl<'a> MatchedCalibration<'a> {
...
     }
 
-    /// Return all [`MeasureCalibrationDefinition`]s in the set
-    pub fn measure_calibrations(&self) -> &[MeasureCalibrationDefinition] {
-        self.measure_calibrations.as_ref()
+    /// Return a vector containing a reference to all [`MeasureCalibrationDefinition`]s
+    /// in the set.
+    pub fn measure_calibrations(&self) -> Vec<&MeasureCalibrationDefinition> {
+        self.measure_calibrations.iter().collect()
+    }
```
Comment (Shadow53) [inline quil-rs/src/program/calibration.rs:70]:
```suggestion
    pub fn measure_calibrations(&self) -> Vec<&MeasureCalibrationDefinition> {
        self.iter_measure_calibrations().collect()
    }
```

**Review by Shadow53 — COMMENTED** [review]
Left a couple small suggestions for consistency, but are fine to ignore.

I'm curious about the implementation of `CalibrationSet`. Maintaining insertion order is nice, but is there a specific use case beyond stable ordering?

I was imagining this would be implemented by sorting the calibrations in the `Vec`.

1. Searching for an item (`get`, `remove`) could be done with a binary search instead of linear (i.e. [`Vec::binary_search_by_key`](https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#method.binary_search_by_key)
2. Equality could be derived, as the same calibrations would be in the same order, regardless of insertion order.
3. Insertion would be less performant due to sorting on insertion.

**Comment by MarquessV** [comment]
> Left a couple small suggestions for consistency, but are fine to ignore.
> 
> I'm curious about the implementation of `CalibrationSet`. Maintaining insertion order is nice, but is there a specific use case beyond stable ordering?
> 
> I was imagining this would be implemented by sorting the calibrations in the `Vec`.
> 
>     1. Searching for an item (`get`, `remove`) could be done with a binary search instead of linear (i.e. [`Vec::binary_search_by_key`](https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#method.binary_search_by_key)
> 
>     2. Equality could be derived, as the same calibrations would be in the same order, regardless of insertion order.
> 
>     3. Insertion would be less performant due to sorting on insertion.

Maintaining insertion has two intents:

1. User preference: Re-ordering the user's instructions seems to be a source of confusion. However, I think the minimum ask is that serialization deterministic.
2. My assumption is that insertion performance would be preferred to equality and serialization performance. Is that not true?

File: quil-rs/src/instruction/calibration.rs [hunk 4]
```diff
@@ -9,6 +9,12 @@ use crate::{
 
 use super::write_qubit_parameters;
 
+pub trait CalibrationSignature {
+    type Signature: PartialEq;
+
+    fn signature(&self) -> Self::Signature;
+}
+
```
Comment (Shadow53) [inline quil-rs/src/instruction/calibration.rs:17]: If you do something like this, we could return references and wouldn't need to clone in the implementations (not tested):

```suggestion
pub trait CalibrationSignature {
    type Signature<'a>: PartialEq;

    fn signature<'a>(&'a self) -> Self::Signature<'a>;
}
```

**Comment by Shadow53** [comment]
> > Left a couple small suggestions for consistency, but are fine to ignore.
> > I'm curious about the implementation of `CalibrationSet`. Maintaining insertion order is nice, but is there a specific use case beyond stable ordering?
> > I was imagining this would be implemented by sorting the calibrations in the `Vec`.
> > ```
> > 1. Searching for an item (`get`, `remove`) could be done with a binary search instead of linear (i.e. [`Vec::binary_search_by_key`](https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#method.binary_search_by_key)
> > 
> > 2. Equality could be derived, as the same calibrations would be in the same order, regardless of insertion order.
> > 
> > 3. Insertion would be less performant due to sorting on insertion.
> > ```
> 
> Maintaining insertion has two intents:
> 
> 1. User preference: Re-ordering the user's instructions seems to be a source of confusion. However, I think the minimum ask is that serialization deterministic.
> 2. My assumption is that parsing and insertion performance would be preferred to equality  performance. Is that not true?

I took a closer look at the implementation, because you are right that insertion performance makes sense to prefer over equality. I'm not sure it's actually currently faster than it would be when sorted, though.

Insertion uses the `replace` function, which is:

```rust
pub fn replace(&mut self, value: T) -> Option<T> {
    if let Some(index) = self.signature_position(value.signature()) {
        let replaced = std::mem::replace(&mut self.data[index], value);
        Some(replaced)
    } else {
        self.data.push(value);
        None
    }
}
```

And `signature_position` is:

```rust
fn signature_position(
    &self,
    signature: <T as CalibrationSignature>::Signature,
) -> Option<usize> {
    self.data
        .iter()
        .position(|element| element.signature() == signature)
}
```

So on every insert, the list is traversed linearly, giving us O(n) performance. `signature` can also clone lists (though somewhat cheaply due to the types involved), so there's a potential performance hit as well (that's a separate issue, which I'll comment on in the code).

If the list were sorted, `signature_position` becomes O(log n) due to binary search. If an entry exists, the performance remains O(log n) due to `mem::replace`. If it does not exist, we'd use `Vec::insert` to insert in the correct location, possibly shifting items, which brings us back to O(n).

Maybe I've analyzed this wrong? I agree that insertion performance is more important, so whatever we merge should be faster at insertion.

> Re-ordering the user's instructions seems to be a source of confusion

I can see that in the case of `HashSet`/`HashMap`, but that's a random re-ordering. I feel like users would be less confused if the reordering was in alphabetical order, or similar.

**Comment by MarquessV** [comment]
> So on every insert, the list is traversed linearly, giving us O(n) performance...
> 
> If the list were sorted, `signature_position` becomes O(log n) due to binary search. If an entry exists, the performance remains O(log n) due to `mem::replace`. If it does not exist, we'd use `Vec::insert` to insert in the correct location, possibly shifting items, which brings us back to O(n).
> 
> Maybe I've analyzed this wrong? I agree that insertion performance is more important, so whatever we merge should be faster at insertion.

With the assumption that inserting a new calibration, rather than one with an existing signature is a much more common case (and is definitely the more useful case): Inserting a new calibration into the vector requires shifting any element in the vector that should be after it, which I think is where the performance would suffer the most with the sort approach. They both have the same time complexity, but appending to a Vec is significantly less work than shifting items in a Vec.

We're getting into the weeds with this, and these kinds of differences need benchmarks to really evaluate. I'd be open to testing that, but I don't want to slow down delivery of a useful feature if there isn't a clear reason to churn on the implementation details.

> > Re-ordering the user's instructions seems to be a source of confusion
> 
> I can see that in the case of `HashSet`/`HashMap`, but that's a random re-ordering. I feel like users would be less confused if the reordering was in alphabetical order, or similar.

I hear you, but that's not the impression I've gathered from users.

File: quil-rs/src/instruction/calibration.rs (hunk 4 above)
Comment (MarquessV) [reply quil-rs/src/instruction/calibration.rs:17]: Nice, I recall trying this without any luck. Will give it another shot.

Comment (MarquessV) [reply quil-rs/src/instruction/calibration.rs:17]: Okay, I found the issue again. The provided snippet isn't valid, as Rust doesn't recognize the lifetime `'a` without defining it as a generic parameter to the trait. When you do provide it, it complains that the `'a` in `Signature` shadows the parameter.

I can get further with this definition:

```rs
pub trait CalibrationSignature<'a> {
    type Signature: PartialEq + 'a;

    fn signature(&'a self) -> Self::Signature;
}
```

But I can't figure out how to convince Rust that the lifetimes in the replace method is okay:

```rs
impl<'a, T> CalibrationSet<T>
where
    T: CalibrationSignature<'a>,
{
    // ...
    pub fn replace(&mut self, value: T) -> Option<T> {
        if let Some(index) = self.signature_position(value.signature()) {
            let replaced = std::mem::replace(&mut self.data[index], value);
            Some(replaced)
        } else {
            self.data.push(value);
            None
        }
    }
}
```

Errors with:

```sh
error[E0597]: `value` does not live long enough
   --> quil-rs/src/program/calibration_set.rs:109:54
    |
58  | impl<'a, T> CalibrationSet<T>
    |      -- lifetime `'a` defined here
...
105 |     pub fn replace<'b>(&'b mut self, value: T) -> Option<T>
    |                                      ----- binding `value` declared here
...
109 |         if let Some(index) = self.signature_position(value.signature()) {
    |                                                      ^^^^^------------
    |                                                      |
    |                                                      borrowed value does not live long enough
    |                                                      argument requires that `value` is borrowed for `'a`
...
116 |     }
    |     - `value` dropped here while still borrowed

error[E0505]: cannot move out of `value` because it is borrowed
   --> quil-rs/src/program/calibration_set.rs:110:69
    |
58  | impl<'a, T> CalibrationSet<T>
    |      -- lifetime `'a` defined here
...
105 |     pub fn replace<'b>(&'b mut self, value: T) -> Option<T>
    |                                      ----- binding `value` declared here
...
109 |         if let Some(index) = self.signature_position(value.signature()) {
    |                                                      -----------------
    |                                                      |
    |                                                      borrow of `value` occurs here
    |                                                      argument requires that `value` is borrowed for `'a`
110 |             let replaced = std::mem::replace(&mut self.data[index], value);
    |                                                                     ^^^^^ move out of `value` occurs here

error[E0505]: cannot move out of `value` because it is borrowed
   --> quil-rs/src/program/calibration_set.rs:113:28
    |
58  | impl<'a, T> CalibrationSet<T>
    |      -- lifetime `'a` defined here
...
105 |     pub fn replace<'b>(&'b mut self, value: T) -> Option<T>
    |                                      ----- binding `value` declared here
...
109 |         if let Some(index) = self.signature_position(value.signature()) {
    |                                                      -----------------
    |                                                      |
    |                                                      borrow of `value` occurs here
    |                                                      argument requires that `value` is borrowed for `'a`
...
113 |             self.data.push(value);
```

There are similar lifetime issues in signature_position(), and some of the trait implementations, but I suspect if we can fix this, we can fix the others.

**Comment by Shadow53** [comment]
Fair enough. I'm happy to punt this discussion to a later time.

**Comment by mhodson-rigetti** [comment]
> > > Re-ordering the user's instructions seems to be a source of confusion
> > 
> > I can see that in the case of `HashSet`/`HashMap`, but that's a random re-ordering. I feel like users would be less confused if the reordering was in alphabetical order, or similar.
> 
> I hear you, but that's not the impression I've gathered from users.

Enforced lexical order in the Quil-T components of the program would be contrary to the [Quil specification](https://quil-lang.github.io/#12-6Defining-Calibrations) in at least one case: "Multiple calibration definitions can be defined for different parameter and qubit values. When a gate is translated into control instructions the calibration definitions are enumerated in reverse order of definition and the first match will be taken." User insertion order must be preserved to obtain the intended translation result.

I think `quil-rs` takes some convenient interpretive decisions such as understanding all frame definitions are global and independent, and so places them up-front in the output in some (currently unspecified) order. This makes no difference to the translation result (at least as far as the specification is concerned) but also backs us in to a place where semantics based on the order cannot be proposed (practically) in the specification without also changing this implementation.

In Quil, I can write pretty much any instruction type in any order, and it is valid. Ideally, the `quil-rs` program would preserve this ordering. Non-deterministic ordering is the key issue here, because on any test failure of program comparison, the very next thing is to debug by comparing the textual Quil inputs and outputs. These cannot be reliably compared if output is non-deterministic. These can be compared if it is deterministic, but then the user must also pre-prepare the input using `quil-rs` to assure the same order- ie. Quil in textual form with a DEFFRAME at the end of the program will never be produced by this library.

A fully general solution would be to use a linked list for all instructions of all types (allowing a DEFFRAME at the end if that is what the user wrote, even though it has global scope in translation), and have the Program additionally index the instructions with (internally unordered) sets or maps keyed by the identity of e.g. DEFFRAME, DEFCAL, DEFGATE, etc to support O(log N) lookup. A linked list of instruction would be needed here as it permits a single O(log N) set update on insertion or deletion of a relevant type of instruction- a vector insert would need to reindex everything at O(N.log N) (which is worse than the insert itself).

At some scale of system you could imagine needing a syntactic ordering constraint- ie. that all objects referred to by an instruction are defined prior to that instruction, so the entire program is not needed first in memory and all indices built, but that's possibly for the future and would need tightening of the specification first.

**Comment by kalzoo** [comment]
To follow up here, equality should _not_ be independent of ordering. Ordering of calibrations can change the way that they are applied within the program and thus are inherently not equal to one another.

Consider:

```
DEFCAL A(%x, pi):
   ...

DEFCAL A(pi, %x):
   ...

A(pi, pi) # expands into one or the other based on ordering
```

These two calibrations are of equivalent precedence and thus ordering makes the difference in which is applied to the gate. They should not be considered equal.
