### PR TITLE
Frame calculations for RESET

### LINKED ISSUE #33: Support RESET Instructions
`RESET` instructions are properly parsed, but their "used frames" are computed as `None`. This is incorrect - a `RESET` acts on the following frames:

1. If a qubit is specified, it acts on frames which use exactly that qubit, and blocks all frames which intersect that qubit
2. If no qubit is specified, apply rule # 1 to all qubits used in the program.

This is an over-simplification in that the implementation of `RESET` is backend-dependent and thus may act on a smaller number of frames than described here. However, this model will allow the timing of a user's program to be properly modeled on the client side.

### PR DESCRIPTION
**Pull request by kalzoo**
Simple approach to RESET frame calculation support as described in the issue.

Reviewers:

- Does this approach make sense?
- Are there cases in which "overly greedy" blocking of frames as computed here in `quil-rs` will cause issues in compilation or elsewhere downstream?

Closes #33 

Linked to #128 for use in tandem downstream.

### CODE REVIEW

File: src/instruction.rs [hunk 1]
```diff
@@ -1178,18 +1181,35 @@ impl Instruction {
...
             } else {
-                FrameMatchCondition::AnyOfQubits(qubits)
+                FrameMatchCondition::AnyOfQubits(Cow::Borrowed(qubits))
             }),
+            Instruction::Reset(Reset { qubit }) => {
+                let qubits = match qubit {
+                    Some(qubit) => {
+                        let mut set = HashSet::new();
+                        set.insert(qubit.clone());
+                        set
```
Comment (genos) [inline src/instruction.rs:1201]: `Hashset::from([qubit.clone()])` or `[qubit.clone()].into()`.

File: src/program/frame.rs [hunk 2]
```diff
@@ -12,7 +12,10 @@
 // See the License for the specific language governing permissions and
 // limitations under the License.
 
-use std::collections::{HashMap, HashSet};
+use std::{
+    borrow::Cow,
```
Comment (genos) [inline src/program/frame.rs:16]: Why is the 🐮 stuff necessary?

**Review by genos — COMMENTED** [review]
One comment, one question

**Review by notmgsk — APPROVED** [review]
