### PR TITLE
fix: use internal QuotedString wrapper to quote Quil strings correctly

### LINKED ISSUE #315: String serialization output does not match spec.
The [quil spec](quil-lang.github.io) specifies that a String is made up of a series of characters inside of double quotation marks, with escape characters `\"` and `\\`.

`quil-rs` currently uses a debug-printed string to handle the quotation marks and escaping, but it escapes too much.

This is a valid string in Quil:

```
"   This is
 a multi-line
string
"
```

But `quil-rs` will encode it as `"   This is\n a multi-line\nstring\n"`, which can cause errors when parsing it later in downstream projects.

### PR DESCRIPTION
**Pull request by Shadow53**
Fixes #315.

This uses a new `QuotedString` wrapper with a custom `Display` impl to only escape quotation marks and backslashes in strings, and nothing else.

### CODE REVIEW

**Comment by kalzoo** [comment]
Thanks for the clear writeup and the fix with a test!

**Review by kalzoo — APPROVED** [review]

File: quil-rs/src/instruction/mod.rs [hunk 1]
```diff
@@ -319,6 +319,25 @@ impl Quil for Instruction {
...
+{
+    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
+        write!(f, "\"")?;
+        for c in self.0.as_ref().chars() {
+            match c {
+                '"' => write!(f, "\\\"")?,
+                '\\' => write!(f, "\\\\")?,
+                c => write!(f, "{}", c)?,
+            }
+        }
```
Comment (BatmanAoD) [inline quil-rs/src/instruction/mod.rs:336]: I suspect `String::replace` would be faster than this, but we'd need to benchmark it. I don't know how much the performance of this conversion matters, though.

Comment (Shadow53) [reply quil-rs/src/instruction/mod.rs:336]: This is specifically inside of `Display`, so I think this might actually be faster. `String::replace` would be creating a new owned `String` and then calling _its_ `Display`, which probably looks similar to this loop.

Comment (BatmanAoD) [reply quil-rs/src/instruction/mod.rs:336]: Ah, fair point. 👍🏻
