### PR TITLE
fix!: tokenize keywords and identifiers correctly

### LINKED ISSUE #427: Identifiers cannot begin with a keyword
When parsing keywords, `quil-rs` does not correctly tokenize its input; the input `BITS` will be parsed as the keyword `BIT` followed by the identifier `S`, and so it can't be used.  For example, `MOVE BITS 0` fails with `"expected Identifier, found DATATYPE(BIT)"`

```
> cargo run -q -- parse "MOVE BITS 0"                                                            round-trip-fails-on-mut|?5⚑2
Error: Failed to parse program from input string.

Caused by:
    0: error while parsing: at line 1, column 1 (COMMAND(MOVE)): failed to parse arguments for MOVE
    1: error while parsing: at line 1, column 1 (COMMAND(MOVE)): failed to parse arguments for MOVE
    2: error while parsing: at line 1, column 1 (COMMAND(MOVE)): failed to parse arguments for MOVE
    3: at line 1, column 1 (COMMAND(MOVE)): failed to parse arguments for MOVE
    4: at line 1, column 6 (DATATYPE(BIT)): expected Identifier, found DATATYPE(BIT)
```

### PR DESCRIPTION
**Pull request by antalsz**
Fix the tokenization of identifiers and keywords so that keywords are not parsed within word boundaries.  Previously, `BITS` would be parsed as the data type `BIT` followed by the identifier `S`; now, it is correctly parsed as the single identifier `BITS`.

This also fixes the tokenization of `NaN`, `Inf`, and `Infinity`; previously, these were case-insensitively parsed as floats (with the same incorrect prefix behavior, so `nana` would parse as the float `NaN` followed by the identifier `a`), but now they are correctly parsed as normal identifiers.

Finally, this PR makes the "mut" keyword lowercase-only.

Closes #427

### CODE REVIEW

File: quil-rs/src/parser/lexer/mod.rs [hunk 1]
```diff
@@ -568,7 +489,13 @@ mod tests {
...
                 Token::Operator(Operator::Minus),
                 Token::Variable("var".to_string())
-        ])
+        ]),
+        case("BIT", vec![Token::DataType(DataType::Bit)]),
+        case("BITS", vec![Token::Identifier("BITS".to_string())]),
+        case("NaN", vec![Token::Identifier("NaN".to_string())]),
+        case("nan", vec![Token::Identifier("nan".to_string())]),
+        case("NaNa", vec![Token::Identifier("NaNa".to_string())]),
+        case("nana", vec![Token::Identifier("nana".to_string())]),
```
Comment (jselig-rigetti) [inline quil-rs/src/parser/lexer/mod.rs:498]: would be worth adding cases for `-Infinity, Infinity, -Inf, Inf` to validate the comment from https://github.com/rigetti/quil-rs/pull/428/files#diff-a5bcc7a39fd5fe75b07e825fc96eeaa32b6cbed091f5936b09d97f9e9112769eR174

File: quil-rs/src/parser/token.rs [hunk 2]
```diff
@@ -67,6 +67,78 @@ where
     }
 }
 
+/// The subset of [`Token`]s which (a) do not contain more specific data and (b) are keywords.  Used
```
Comment (jselig-rigetti) [inline quil-rs/src/parser/token.rs:70]: what does `more specific data` mean here? Like arguments?

File: quil-rs/src/parser/token.rs [hunk 3]
```diff
@@ -67,6 +67,78 @@ where
...
+        }
+    }
+}
+
+impl TryFrom<Token> for KeywordToken {
+    type Error = ();
+
+    fn try_from(token: Token) -> Result<Self, Self::Error> {
+        // This match is explicit so that if you add a new [`Token`] constructor you have to decide
+        // if it's a keyword.  Please do not add a top-level wildcard match here.
```
Comment (jselig-rigetti) [inline quil-rs/src/parser/token.rs:107]: Would adding `#![deny(clippy::wildcard_enum_match_arm)]` work?

File: quil-rs/src/reserved.rs [hunk 4]
```diff
@@ -20,79 +25,36 @@ impl FromStr for ReservedToken {
...
-        if let Ok(keyword) = ReservedKeyword::from_str(s) {
-            Ok(Self::Keyword(keyword))
-        } else if let Ok(gate) = ReservedGate::from_str(s) {
-            Ok(Self::Gate(gate))
-        } else if let Ok(constant) = ReservedConstant::from_str(s) {
-            Ok(Self::Constant(constant))
-        } else {
-            Err(NotReservedToken(s.to_string()))
+        fn parse<T: FromStr>(
+            reserved: impl Fn(T) -> ReservedToken,
```
Comment (jselig-rigetti) [inline quil-rs/src/reserved.rs:29]: Can the `Self` type be used here? Not saying it would be better, just curious the scoping

```suggestion
            reserved: impl Fn(T) -> Self,
```

**Review by jselig-rigetti — APPROVED** [review]
Really clean changes! LGTM pending CI errors

File: quil-rs/src/parser/token.rs (hunk 2 above)
Comment (antalsz) [reply quil-rs/src/parser/token.rs:70]: Yes, that’s a better way to say it, thanks!

File: quil-rs/src/parser/token.rs (hunk 3 above)
Comment (antalsz) [reply quil-rs/src/parser/token.rs:107]: Oh perfect, I didn’t know about that!

File: quil-rs/src/reserved.rs (hunk 4 above)
Comment (antalsz) [reply quil-rs/src/reserved.rs:29]: It actually can’t – I wrote it that way first, but you get “error[E0401]: can't use `Self` from outer item”.

File: quil-rs/src/parser/lexer/mod.rs (hunk 1 above)
Comment (antalsz) [reply quil-rs/src/parser/lexer/mod.rs:498]: Done, and they correctly pass – thanks!
